// Lightweight real browser CAD engine for IA-Tutor.
// Geometry is stored as editable entities rather than a screenshot/animation.
export class RealCadEngine {
  constructor(svg) { this.svg=svg; this.entities=[]; this.history=[]; this.future=[]; this.grid=10; this.snap=true; }
  point(x,y){return this.snap?[Math.round(x/this.grid)*this.grid,Math.round(y/this.grid)*this.grid]:[x,y];}
  add(entity){this.history.push(JSON.stringify(this.entities));this.future=[];this.entities.push({id:crypto.randomUUID(),...entity});this.render();return this.entities.at(-1);}
  line(x1,y1,x2,y2,props={}){const a=this.point(x1,y1),b=this.point(x2,y2);return this.add({type:'line',x1:a[0],y1:a[1],x2:b[0],y2:b[1],layer:props.layer||'Object',construction:!!props.construction});}
  rectangle(x,y,width,height,props={}){const a=this.point(x,y);return this.add({type:'polyline',points:[[a[0],a[1]],[a[0]+width,a[1]],[a[0]+width,a[1]+height],[a[0],a[1]+height],[a[0],a[1]]],layer:props.layer||'Object'});}
  circle(cx,cy,r,props={}){const a=this.point(cx,cy);return this.add({type:'circle',cx:a[0],cy:a[1],r,layer:props.layer||'Object'});}
  dimension(x1,y1,x2,y2,label,props={}){return this.add({type:'dimension',x1,y1,x2,y2,label:String(label),layer:props.layer||'Dimensions'});}
  clear(){this.history.push(JSON.stringify(this.entities));this.entities=[];this.future=[];this.render();}
  undo(){if(!this.history.length)return;this.future.push(JSON.stringify(this.entities));this.entities=JSON.parse(this.history.pop());this.render();}
  redo(){if(!this.future.length)return;this.history.push(JSON.stringify(this.entities));this.entities=JSON.parse(this.future.pop());this.render();}
  render(){if(!this.svg)return;this.svg.innerHTML='';for(const e of this.entities){const tag=e.type==='circle'?'circle':e.type==='polyline'?'polyline':e.type==='dimension'?'g':'line';const n=document.createElementNS('http://www.w3.org/2000/svg',tag);n.classList.add('cad-entity');if(e.type==='line')Object.entries({x1:e.x1,y1:e.y1,x2:e.x2,y2:e.y2}).forEach(([k,v])=>n.setAttribute(k,v));if(e.type==='circle'){n.setAttribute('cx',e.cx);n.setAttribute('cy',e.cy);n.setAttribute('r',e.r);}if(e.type==='polyline')n.setAttribute('points',e.points.map(p=>p.join(',')).join(' '));if(e.type==='dimension'){const l=document.createElementNS('http://www.w3.org/2000/svg','line');l.setAttribute('x1',e.x1);l.setAttribute('y1',e.y1);l.setAttribute('x2',e.x2);l.setAttribute('y2',e.y2);l.classList.add('cad-dim-line');const t=document.createElementNS('http://www.w3.org/2000/svg','text');t.setAttribute('x',(e.x1+e.x2)/2);t.setAttribute('y',(e.y1+e.y2)/2-6);t.classList.add('cad-dim-text');t.textContent=e.label;n.append(l,t);}this.svg.appendChild(n);}}
}

export function buildAutomaticOrthographicCad(engine,{width,height,depth,units='mm'}){if(![width,height,depth].every(v=>Number.isFinite(Number(v))&&Number(v)>0))throw new Error('AI must provide width, height and depth before CAD generation.');const W=Number(width),H=Number(height),D=Number(depth),ox=60,oy=60,gap=70;engine.clear();engine.rectangle(ox,oy,W,H);engine.rectangle(ox,oy+H+gap,W,D);engine.rectangle(ox+W+gap,oy,D,H);engine.line(ox,oy+H,ox,oy+H+gap,{construction:true});engine.line(ox+W,oy+H,ox+W,oy+H+gap,{construction:true});engine.line(ox+W,oy,ox+W+gap,oy,{construction:true});engine.line(ox+W,oy+H,ox+W+gap,oy+H,{construction:true});engine.dimension(ox,oy-20,ox+W,oy-20,`${W} ${units}`);engine.dimension(ox-20,oy,ox-20,oy+H,`${H} ${units}`);engine.dimension(ox,oy+H+D+20,ox+W,oy+H+D+20,`${W} ${units}`);engine.dimension(ox+W+gap,oy-20,ox+W+gap+D,oy-20,`${D} ${units}`);return engine.entities;}
